
INSERT INTO `directory_country_region` (`region_id`, `country_id`, `code`, `default_name`) VALUES
(NULL, 'VN', 'HCMC', 'Hồ Chí Minh' ) ,
(NULL, 'VN', 'HN', 'Hà Nội' ) ,
(NULL, 'VN', 'AG', 'An Giang' ) ,
(NULL, 'VN', 'BRVT', 'Bà Rịa Vũng Tàu' ) ,
(NULL, 'VN', 'BK', 'Bắc Kạn' ) ,
(NULL, 'VN', 'BL', 'Bạc Liêu' ) ,
(NULL, 'VN', 'BN', 'Bắc Ninh' ) ,
(NULL, 'VN', 'BT', 'Bến Tre' ) ,
(NULL, 'VN', 'BD', 'Bình Dương' ) ,
(NULL, 'VN', 'BP', 'Bình Phước' ) ,
(NULL, 'VN', 'BTH', 'Bình Thuận' ) ,
(NULL, 'VN', 'BDH', 'Bình Định' ) ,
(NULL, 'VN', 'CM', 'Cà Mau' ) ,
(NULL, 'VN', 'CT', 'Cần Thơ' ) ,
(NULL, 'VN', 'CB', 'Cao Bằng' ) ,
(NULL, 'VN', 'GL', 'Gia Lai' ) ,
(NULL, 'VN', 'HG', 'Hà Giang' ) ,
(NULL, 'VN', 'HNAM', 'Hà Nam' ) ,
(NULL, 'VN', 'HT', 'Hà Tĩnh' ) ,
(NULL, 'VN', 'HH', 'Hải Dương' ) ,
(NULL, 'VN', 'HP', 'Hải Phòng' ) ,
(NULL, 'VN', 'HGG', 'Hậu Giang' ) ,
(NULL, 'VN', 'HB', 'Hòa Bình' ) ,
(NULL, 'VN', 'HY', 'Hưng Yên' ) ,
(NULL, 'VN', 'KH', 'Khánh Hòa' ) ,
(NULL, 'VN', 'KG', 'Kiên Giang' ) ,
(NULL, 'VN', 'KT', 'Kon Tum' ) ,
(NULL, 'VN', 'LCU', 'Lai Châu' ) ,
(NULL, 'VN', 'LD', 'Lâm Đồng' ) ,
(NULL, 'VN', 'LS', 'Lạng Sơn' ) ,
(NULL, 'VN', 'LC', 'Lào Cai' ) ,
(NULL, 'VN', 'LA', 'Long An' ) ,
(NULL, 'VN', 'ND', 'Nam Định' ) ,
(NULL, 'VN', 'NA', 'Nghệ An' ) ,
(NULL, 'VN', 'NB', 'Ninh Bình' ) ,
(NULL, 'VN', 'NT', 'Ninh Thuận' ) ,
(NULL, 'VN', 'PT', 'Phú Thọ' ) ,
(NULL, 'VN', 'PY', 'Phú Yên' ) ,
(NULL, 'VN', 'QB', 'Quảng Bình' ) ,
(NULL, 'VN', 'QN', 'Quảng Nam' ) ,
(NULL, 'VN', 'QNG', 'Quảng Ngãi' ) ,
(NULL, 'VN', 'QNH', 'Quảng Ninh' ) ,
(NULL, 'VN', 'QTR', 'Quảng Trị' ) ,
(NULL, 'VN', 'ST', 'Sóc Trăng' ) ,
(NULL, 'VN', 'SL', 'Sơn La' ) ,
(NULL, 'VN', 'TN', 'Tây Ninh' ) ,
(NULL, 'VN', 'TB', 'Thái Bình' ) ,
(NULL, 'VN', 'TNG', 'Thái Nguyên' ) ,
(NULL, 'VN', 'TH', 'Thanh Hóa' ) ,
(NULL, 'VN', 'TTH', 'Thừa Thiên Huế' ) ,
(NULL, 'VN', 'TG', 'Tiền Giang' ) ,
(NULL, 'VN', 'TV', 'Trà Vinh' ) ,
(NULL, 'VN', 'TQ', 'Tuyên Quang' ) ,
(NULL, 'VN', 'VL', 'Vĩnh Long' ) ,
(NULL, 'VN', 'VP', 'Vĩnh Phúc' ) ,
(NULL, 'VN', 'YB', 'Yên Bái' ) ,
(NULL, 'VN', 'DNG', 'Đà Nẵng' ) ,
(NULL, 'VN', 'DL', 'Đăk Lăk' ) ,
(NULL, 'VN', 'DKN', 'Đăk Nông' ) ,
(NULL, 'VN', 'DB', 'Điện Biên' ) ,
(NULL, 'VN', 'DN', 'Đồng Nai' ) ,
(NULL, 'VN', 'DT', 'Đồng Tháp');